config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
#  root 'products#index'

# strange error appeared after upgrade to rails 6, hence this next line
  get '/active', to: proc { [200, {}, ['']] }

  devise_for :users, controllers: { registrations: "my_registrations" } 
  get '/users/', to: 'users#index'
  get '/switch_to/:id', to: 'users#switch_to', as: :switch_user
  get '/suppliers/index'
  get '/managers/index'
  get '/inventories', to: 'inventories#index'
  post '/update_stock/:id', to: 'products#update_stock', as:  :update_stock 
  post '/update_delta/:id', to: 'products#update_delta', as:  :update_delta 
  post '/apply_price_rules_to_products', to: 'products#apply_price_rules', as:  :apply_price_rules_to_products
  post '/apply_price_rules_to_orders', to: 'orders#apply_price_rules', as:  :apply_price_rules_to_orders
  get '/reports', to: 'reports#index'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  
  post '/add_product(/:id)', to: 'placements#add_product', as: :add_product
  get '/cart', to: 'placements#cart', as: :cart
  get '/empty_cart', to: 'placements#empty_cart', as: :empty_cart
  get '/delete_product(/:id)', to: 'placements#delete_product', as: :delete_product
  post '/update_product_qty(/:id)', to: 'placements#update_product_qty', as: :update_product_qty

  get '/image_upload', to: 'products#image_upload'
  post '/upload_image', to: 'products#upload_image'

  get '/self_test', to: 'self_test#index', as: :self_test

  resources :suppliers, :managers, :shippers, :users, :prices, :table_notes
  resources :products do
    get 'show_pending_orders', on: :member 
    get 'show_active_orders', on: :member 
#    post 'clear_active_order', on: :member
    post 'set_pending_orders_to_shipped', on: :member
    get 'disable', on: :member
    resources :ppos, only: [:index, :show, :create, :destroy] 
  end

# extra ppo paths  
  resources :ppos, only: [:index, :show, :create] do
    get 'show_placements', on: :member 
    post 'set_to_shipped', on: :member
    get 'export', on: :member
    get 'download', on: :member
  end

  resources :'packing_lists' do 
     get 'download', on: :member
     patch 'ship', on: :member
  end

  get '/inventory_template', to: 'products#inventory_template'
  get '/show_inventory', to: 'products#show_inventory'
  resources :inventories do
    get 'download', on: :member
  end

  get '/export_orders', to: 'orders#export' 
  get '/export_ppos', to: 'ppos#export' 

  resources :orders do
    get 'download_po', on: :member
    get 'download_invoice', on: :member
    get 'cancel', on: :member
    patch 'set_to_shipped', on: :member
    patch 'mark_as_paid', on: :member
  end

  resources :placements do
#      patch 'set_to_shipped', on: :member
#      get 'set_to_shipped', on: :member  # for redirect_to in placements#update_shipped
      patch 'update_shipped', on: :member
      get 'cancel', on: :member
   end

  resources :clients do
    get 'send_invite_to_register', on: :member
  end 

  resources :reports  do
     get 'download', on: :member
     get 'export', on: :member
  end

  resources :client_mails do
    get 'show_target', on: :member  # show target clients in client mailer
    get 'send_all', on: :member
    get 'send_staff', on: :member
  end

end

app/models/packing_list.rb
class PackingList < ApplicationRecord
  belongs_to :user
  has_many :placements
        
  mount_uploader :csv, PlistCsvUploader
  validate :validate_csv_file, on: :create 
  
  default_scope -> { order(status: :asc, created_at: :desc) }
  
  def csv_file_present?
    File.exists?(self.csv_path)
  end

  def csv_path
    PLISTS_PATH.join(self.filename) rescue nil
#   self.csv.to_s
  end

  def filespec
    csv_path
  end

  def exists?
    File.exists?(self.filespec) rescue false
  end

  def status_str
    PLIST_STATUSES.invert[self.status].to_s rescue nil
  end

# Return array of lines from CSV   
  def contents
    self.csv.read.split("\r\n") rescue nil
  end 

  def filename
    self.csv.identifier
  end

  def active?
    self.status == ACTIVE_PLIST
  end

  def archived?
    self.status == ARCHIVED_PLIST
  end

  def self.any_active?
    self.exists?(status: ACTIVE_PLIST)
  end

private 

# Calculate total number of lines & pieces in this plist  N.B! Header line: "Order", "Ref_code", "Pcs" 
# Verify CSV file syntax and validity of data
# Add placements and set "to_ship" quantity

  def validate_csv_file
    require 'csv'
    require 'digest'

    (errors.add(:packing_list, ": No CSV name"); return) unless self.name.present?
    csv_text = File.read( self.csv_path ) 
    (errors.add(:packing_list, ": Could not read CSV file #{self.csv_path}"); return) unless csv_text

    md5 = Digest::MD5.file(self.csv_path).to_s rescue nil
    pl = PackingList.find_by(md5: md5) if md5
    (errors.add(:file_exists, ": This packing list was already uploaded (#{pl.name})"); return) if pl

    csv = CSV.parse(csv_text, :headers => true, :encoding => 'ISO-8859-1')
    (errors.add(:file_format, "CSV file format error"); return) unless csv

    (errors.add(:file_format_error, "This is not Comma-Separated Vaue file (#{csv.first[0]}). Fix it and try again"); return) unless csv.first[2].to_i > 0  # pcs column must be integer
    ttl_pcs = lines = pending_active_pcs = 0; products = {}; orders = {};
    csv.each do |row|
      lines +=1
      order_id = row[0].to_i
      (errors.add(:orders, "- line #{lines}: bad order number"); return) if order_id == 0
      order = Order.find(order_id) rescue nil
      (errors.add(:missing_order, "- line #{lines}: order '#{row[0]}' does not exist"); return) unless order.present?
      ref_code = row[1].strip.gsub('"','')
      (errors.add(:products, "line #{lines}: missing product code"); return) unless ref_code.present?
      product = Product.find_by(ref_code: ref_code)
      (errors.add(:products, "- line #{lines}: unknown product code #{ref_code}"); return) unless product
      placement = Placement.find_by(order_id: order_id, product_id: product.id)
      (errors.add(:missing_placement, "- line #{lines}: Placement for order #{order.id}  product #{ref_code} does not exist"); return) unless placement.present?
      pcs = row[2].to_i
      (errors.add(:pcs, "- line #{lines}: bad number of pieces: '#{row[2]}'"); return) if pcs == 0
      pending_active_pcs = order.pending(product.id)
      (errors.add(:wrong_pending_pcs, "- line #{lines}: wrong number of pcs (#{pcs}) to ship for order #{order.id}/#{product.ref_code}: we have #{pending_active_pcs} pending/active pcs  "); return) if pending_active_pcs < pcs
      (errors.add(:insufficient_pcs, "- line #{lines}: insufficient inventory for order #{order.id}/#{product.ref_code}: #{pcs} pcs marked for shipment, we only have #{product.stock} pcs in stock  "); return) if pcs > product.stock
      self.placements.push(placement)
      placement.update_attribute(:to_ship, pcs )
      orders[order_id] = 1 if order_id    
      products[ref_code] = 1 if ref_code  
      ttl_pcs += pcs 
    end
    (errors.add(:no_pcs, "Nothing to ship. Check your file"); return) if ttl_pcs < 1

    return if errors.any?
    self.md5 = md5
    self.lines = lines 
    self.orders = orders.keys.count
    self.products = products.keys.count
    self.pcs = ttl_pcs
 end

end

app/controllers/packing_lists_controller.rb
class PackingListsController < ApplicationController

  before_action :init, only: [:show, :edit, :update, :download, :destroy, :ship ]
  before_action :logged_in_user
  before_action :production_admin_or_staff_user #, only: [:edit, :create, :update ]
  before_action :admin_or_su_user, only: [:destroy]

  def index
    @plists = PackingList.all
  end

  def show
  end

  def new
    @packing_list = PackingList.new
  end

  def create
    csv = params[:file][:file] rescue nil
    fn = csv.original_filename if csv
    name = Pathname(fn).basename('.csv').to_s rescue nil
    PlistCsvUploader.new().store!(csv)

    @plist = PackingList.new(name: name, csv: csv, user_id: current_user.id )
    if @plist.save
      flash[:success] = "New packing list created. 'To ship' quantities updated"
    else
      flash[:danger] = @plist.errors.full_messages.to_sentence
    end

    redirect_to packing_lists_path
  end

  # delete active list, reset placements 'to_ship' attribute.  
  def destroy
    @packing_list.placements.each do |pl|
      pl.update(to_ship: 0, packing_list_id: nil)
    end
    File.delete( @packing_list.filespec ) rescue nil
    flash[:success] = "Packing list #{@packing_list.name} deleted. "
    @packing_list.destroy
    redirect_to packing_lists_path
  end

  def edit
  end

  def update
    if @packing_list.update(packing_list_params)
      flash[:success] = "Packing List updated"
      redirect_back(fallback_location: packing_lists_path)
    else
      render 'edit'
    end
  end

# Ship this packing list: change quantities and statuses  
  def ship
    @packing_list.placements.each do |pl|
      pl.ship_plist
    end
    @packing_list.update_attribute(:status, ARCHIVED_PLIST)
    flash[:success] = "Packing List shipped"
    redirect_to packing_lists_path 
  end

# download CSV  
  def download
    (flash[:warning] = 'Packing list file missing'; redirect_to packing_lists_path; return) unless @packing_list.exists?
    respond_to do |format|
      format.csv { 
           send_file(@packing_list.csv_path,
           filename: @packing_list.filename,
           type: "text/csv",
           disposition: :attachment)    
           }
      format.js
    end

    flash.now[:info] = "CSV file downloaded"
  end

private
  def init
    @packing_list = PackingList.find(params[:id]) rescue nil
    (flash[:warning]="Packing List not found"; redirect_to packing_lists_path) unless @packing_list 
  end

  def packing_list_params
    params.require(:'packing_list').permit( :name, :description, :csv, :lines, :orders, :products, :pcs, :status, :md5 )
  end

end

app/helpers/packing_lists_helper.rb
module PackingListsHelper
end

app/views/packing_lists/_csv_line.html.erb
<% col = csv_line.split(',') %>
<% return unless col[0].to_i > 0 %>
<tr>
  <td class="text-center"> <%= col[0] %> </td>
  <td class="text-center"> <%= col[1] %> </td>
  <td class="text-center"> <%= col[2] %> </td>
</tr>

app/views/packing_lists/_edit.html.erb
<%
   provide(:title, 'Edit Packing List')
   provide(:button_text, 'Save changes')
%>

<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <b class="modal-title" id="myModalLabel"><%= @packing_list.name %> - Edit Packing List</b>
</div>
<div class="modal-body">
       <%= render 'form' %>
</div>

<div class="modal-footer">
</div>

app/views/packing_lists/_form.html.erb
<%= simple_form_for @packing_list do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="row" %>
  <div class="col-md-12">
  <%= f.input :description, as: :text, input_html: {rows:8} %>
  </div>
  </div>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

app/views/packing_lists/_packing_list.html.erb
<tr>
  <td class="text-center"><%= link_to packing_list.name, packing_list %></td>
  <td class="text-center"><%= packing_list.description %></td>
  <td class="text-center"><%= packing_list.created_at.to_date %> </td>
  <td class="text-center"><%= packing_list.orders %></td>
  <td class="text-center"><%= packing_list.products %></td>
  <td class="text-center"><%= packing_list.pcs %></td>
  <td class="text-center"><%= packing_list.user.email %></td>
  <td class="text-center"><%= packing_list.status_str %></td>

  <td class="text-center">
  <% if packing_list.active? %>
    <%= link_to "Ship It", ship_packing_list_path(packing_list), method: :patch, data: { confirm: "About to ship Packing list #{packing_list.name}. This will update pending and shipped quantities as well as order/PPO statuses. Do you want to Proceed?" } %>
  <% else %>
    shipped
  <% end %>
  <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_packing_list_path(packing_list), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %> </td>
  
  <td class="text-center">
  <% unless packing_list.active? %>
    <%= link_to '<i class="glyphicon glyphicon-download"></i>'.html_safe, download_packing_list_path(packing_list, format: :csv) %>
  <% end %>
  </td>
  
  <td class="text-center">
  <% if packing_list.active? %>
  <%= link_to '<i class="glyphicon glyphicon-remove-sign"></i>'.html_safe, packing_list, method: :delete, data: { confirm: "Are you sure you want to delete #{packing_list.name}?" } %>
  <% end %>
  </td>
</tr>

app/views/packing_lists/_placement.html.erb
<tr>
  <td class="text-center"> <%= link_to placement.order_id, placement.order, remote:true, 'data-toggle':  "modal", 'data-target': '#modal-window' %> </td>
  <td class="text-center"> <%= placement.order.client_name %> </td>
  <td class="text-center"> <%= placement.product.ref_code %> </td>
  <td class="text-center"> <%= placement.quantity %> </td>
  <td class="text-center"> <%= placement.to_ship %> </td>
</tr>

app/views/packing_lists/_show_active.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-hover table-striped">
      <caption><%= @packing_list.status_str %> packing List "<%= @packing_list.name %>", uploaded <%= @packing_list.created_at.to_date %> by <%= @packing_list.user.email %></caption>
      <thead>
      <tr>
          <th class="tbl_md, text-center">Order</th>
          <th class="tbl_md, text-center">Client</th>
          <th class="tbl_md, text-center">Ref Code</th>
          <th class="tbl_md text-center">Pcs Ordered</th>
          <th class="tbl_md text-center">To Ship</th>
      </tr>
      </thead>
      <tbody>
        <%= render partial: "placement", collection: @packing_list.placements %>
      </tbody>
      <tfoot>
        <th colspan=3></th>
        <th class="text-center font-weight-bold"><%= @packing_list.placements.sum(:quantity) %></th>
        <th class="text-center font-weight-bold"><%= @packing_list.placements.sum(:to_ship) %></th>
      </tfoot>
    </table>
  </div>
</div>

app/views/packing_lists/_show_csv.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-hover table-striped">
      <caption><%= @packing_list.status_str %> packing List "<%= @packing_list.name %>", uploaded <%= @packing_list.created_at.to_date %> by <%= @packing_list.user.email %></caption>
      <thead>
      <tr>
          <th class="tbl_md, text-center">Order</th>
          <th class="tbl_md, text-center">Ref Code</th>
          <th class="tbl_md text-center">Pcs Shipped</th>
      </tr>
      </thead>
      <tbody>
         <%= render partial: "csv_line", collection: @packing_list.contents %>
      </tbody>
      <tfoot>
        <th colspan=2></th>
        <th class="text-center font-weight-bold"><%= @packing_list.pcs %></th>
      </tfoot>
    </table>
  </div>
</div>

app/views/packing_lists/_upload_form.html.erb
<h4>Packing list upload form</h4>
<div class="well">

  <h5> Please provide comma-separated file with "csv" extension. First 3 columns must be : "Order Number", "Ref Code" and "Number of Pcs to ship". After upload, file will be checked and if valid, "to_ship" attribute will be set in each corresponding placement. This file can be then processed to update quantities and statuses by using "Ship It" link generated. </h5>
  <%= simple_form_for @packing_list, html: {multipart: false, class: "dropzone", id:"my-dropzone"}, method: :post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
<div id='dropzone_panel'>
  <div class="dz-message">Drop csv file here to upload</div>
  <%= f.hint 'If file with identical number of shipped pieces exists on the server, new file will be ignored.' %>
</div>
</form>
</div>
<%= f.button :submit, "Upload", class:"btn btn-block btn-primary", id: "submit", disabled: true %>
<% end %>

<script>
Dropzone.options.myDropzone = {
  paramName: "file[file]",
  acceptedFiles: ".csv,.CSV",
  maxFiles: 1,
  maxFilesize: 145, // MB
  addRemoveLinks: true,
  url: "<%= packing_lists_url %>",
  autoDiscover: true,
  uploadMultiple: false,
  autoProcessQueue: false,
//  autoQueue: false,

init: function() {
    this.on("addedfile", function() { if (this.files[1]!=null){ this.removeFile(this.files[0]); } });
    this.on("success", function(file) { window.location = "<%= packing_lists_path %>"; });
    var submitButton = document.querySelector("#submit")
        myDropzone = this; // closure

    submitButton.addEventListener("click", function() {
      myDropzone.processQueue(); // Tell Dropzone to process all queued files.
    });

    this.on("addedfile", function(file) {
      var submit = document.getElementById('submit');
//    console.log("loaded");
      submit.disabled = false;
    });
}
};
  
</script>

app/views/packing_lists/create.html.erb
<h1>PackingLists#create</h1>
<p>Find me in app/views/packing_lists/create.html.erb</p>

app/views/packing_lists/edit.html.erb
<%
   provide(:button_text, 'Save changes')
%>

<div class="col-md-8 col-md-offset-2">
<h3 class='display-1'>Edit Packing List</h3>
<div class="well">

       <%= render 'form' %>

</div>
</div>

app/views/packing_lists/index.html.erb
<%= render "shared/modal" %>

<table class="table table-hover table-striped" >
  <caption>List of Packing Lists</caption>
  <thead>
      <tr>
          <th class="text-center">Name</th>
          <th class="text-center">Description</th>
          <th class="text-center">Date</th>
          <th class="text-center">Orders</th>
          <th class="text-center">Products</th>
          <th class="text-center">Total Pcs To Ship</th>
          <th class="text-center">Uploaded by</th>
          <th class="text-center">Status</th>
          <th class="text-center">Ship it </th>
          <th></th>
          <th></th>
          <th></th>
      </tr>
  </thead>
  <tbody>

  <%= render partial: 'packing_list', collection: @plists, as: :packing_list, remote: device_is_desktop? %>

  </tbody>
</table>

<div class="bottom_buttons ">
  <% disabled = PackingList.any_active? %> 
  <%= button_to "Upload Packing List", new_packing_list_path, class: "btn btn-primary col-md-2", method: :get, disabled: disabled, title: 'Please ship Active Packing List first'%> 
</div>

app/views/packing_lists/show.html.erb
<%= render "shared/modal" %>

<% if @packing_list.active? %>
  <%= render "show_active" %>
<% else %>
  <%= render "show_csv" %>
<% end %>

app/views/packing_lists/upload.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'upload_form') %>");
$("#modal-window").modal();