config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
#  root 'products#index'

# strange error appeared after upgrade to rails 6, hence this next line
  get '/active', to: proc { [200, {}, ['']] }

  devise_for :users, controllers: { registrations: "my_registrations" } 
  get '/users/', to: 'users#index'
  get '/switch_to/:id', to: 'users#switch_to', as: :switch_user
  get '/suppliers/index'
  get '/managers/index'
  get '/inventories', to: 'inventories#index'
  post '/update_stock/:id', to: 'products#update_stock', as:  :update_stock 
  post '/update_delta/:id', to: 'products#update_delta', as:  :update_delta 
  post '/apply_price_rules_to_products', to: 'products#apply_price_rules', as:  :apply_price_rules_to_products
  post '/apply_price_rules_to_orders', to: 'orders#apply_price_rules', as:  :apply_price_rules_to_orders
  get '/reports', to: 'reports#index'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  
  post '/add_product(/:id)', to: 'placements#add_product', as: :add_product
  get '/cart', to: 'placements#cart', as: :cart
  get '/empty_cart', to: 'placements#empty_cart', as: :empty_cart
  get '/delete_product(/:id)', to: 'placements#delete_product', as: :delete_product
  post '/update_product_qty(/:id)', to: 'placements#update_product_qty', as: :update_product_qty

  get '/image_upload', to: 'products#image_upload'
  post '/upload_image', to: 'products#upload_image'

  get '/self_test', to: 'self_test#index', as: :self_test

  resources :suppliers, :managers, :shippers, :users, :prices, :table_notes
  resources :products do
    get 'show_pending_orders', on: :member 
    get 'show_active_orders', on: :member 
#    post 'clear_active_order', on: :member
    post 'set_pending_orders_to_shipped', on: :member
    get 'disable', on: :member
    resources :ppos, only: [:index, :show, :create, :destroy] 
  end

# extra ppo paths  
  resources :ppos, only: [:index, :show, :create] do
    get 'show_placements', on: :member 
    post 'set_to_shipped', on: :member
    get 'export', on: :member
    get 'download', on: :member
  end

  resources :'packing_lists' do 
     get 'download', on: :member
     patch 'ship', on: :member
  end

  get '/inventory_template', to: 'products#inventory_template'
  get '/show_inventory', to: 'products#show_inventory'
  resources :inventories do
    get 'download', on: :member
  end

  get '/export_orders', to: 'orders#export' 
  get '/export_ppos', to: 'ppos#export' 

  resources :orders do
    get 'download_po', on: :member
    get 'download_invoice', on: :member
    get 'cancel', on: :member
    patch 'set_to_shipped', on: :member
    patch 'mark_as_paid', on: :member
  end

  resources :placements do
#      patch 'set_to_shipped', on: :member
#      get 'set_to_shipped', on: :member  # for redirect_to in placements#update_shipped
      patch 'update_shipped', on: :member
      get 'cancel', on: :member
   end

  resources :clients do
    get 'send_invite_to_register', on: :member
  end 

  resources :reports  do
     get 'download', on: :member
     get 'export', on: :member
  end

  resources :client_mails do
    get 'show_target', on: :member  # show target clients in client mailer
    get 'send_all', on: :member
    get 'send_staff', on: :member
  end

end

app/models/price.rb
class Price < ApplicationRecord
  
  default_scope -> { order(scale: :asc, category: :asc) }

# All prices, except CNY are required:  
  validates :price_eu, :price_eu2, :price_eu3, :price_eu4, :price_eu5, :price_eu6, :price_usd, :price_usd2, presence: true, numericality: true
  validates_uniqueness_of :brand, scope: [:scale, :category], message: ": Rule already present"

  def category_str
    CATEGORIES.invert[self.category] rescue nil
  end
  
  def brand_str
    BRANDS.invert[self.brand] rescue nil
  end
  
  def scale_str
    SCALES.invert[self.scale] rescue nil
  end

end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  
  before_action :logged_in_user
  before_action :admin_or_staff_user
 
  def new
    @price = Price.new
  end

  def index
    @prices = Price.all
    filter = params[:price]
    if filter
      @scale = filter[:scale]
      @brand = filter[:brand]
      @category = filter[:category]
    end 

    @prices = @prices.where(scale: @scale) if @scale.present?
    @prices = @prices.where(brand: @brand) if @brand.present?
    @prices = @prices.where(category: @category) if @category.present?

    @table_note = TableNote.find_by(table_name: 'prices') || TableNote.create('table_name': 'prices')
    @prices = @prices.paginate(page: params[:page])
#    flash[:info] = "scale: #{@scale} brand: #{@brand} cat: #{@category}"
  end

  def create
    @price = Price.new(price_params)
    if @price.save
       flash[:success] = "New price rule created"
       redirect_to prices_path
    else
       render 'new'
    end
  end
  
  def edit
    @price = Price.find(params[:id])
  end

  def update
    @price = Price.find(params[:id])
    if @price.update(price_params)
      flash[:success] = "Price rule updated"
      redirect_to prices_path
    else
      render 'edit'
    end
  end

  def show
    @price = Price.find(params[:id])
    redirect_to prices_path unless @price
  end

  def destroy
    Price.find(params[:id]).destroy
    flash[:success] = "Price rule deleted"
    redirect_to prices_path
  end


private
  def price_params
    params.require(:price).permit( :scale, :category, :brand, :price_eu, :price_eu2, :price_eu3, :price_eu4, :price_eu5, :price_eu6, :price_usd, :price_usd2, :price_cny )
  end  

end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_edit.html.erb
<%
   provide(:title, 'Edit Price')
   provide(:button_text, 'Save changes')
%>

<div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <b class="modal-title" id="myModalLabel"><%= @price.brand_str %>: Scale <%= @price.scale_str %> <%= @price.category_str %> - Edit Price Rule</b>
</div>
<div class="modal-body">
       <%= render 'form' %>
</div>

<div class="modal-footer">
</div>

app/views/prices/_form.html.erb
<%= simple_form_for @price do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <% edit = (action_name == 'edit')? true : false %>  

  Required fields are marked with asterisk
  
  <div class="row pt-3">
    <div class="col-md-3">
    <%= f.input :brand, collection: BRANDS, include_blank: false, disabled: edit %>
    </div>
    <div class="col-md-2">
    <%= f.input :scale, collection: SCALES, include_blank: false, disabled: edit %>
    </div>
    <div class="col-md-2">
    <%= f.input :category, collection: CATEGORIES, include_blank: false, disabled: edit %>
    </div>
  </div>

  <div class="row">
  <div class="col-md-2">
    <%= f.input :price_eu, label: "EU1 Price" %>
  </div>
  
  <div class="col-md-2">
    <%= f.input :price_eu2, label: "EU2 Price" %>
  </div>

  <div class="col-md-2">
    <%= f.input :price_eu3, label: "EU3 Price" %>
  </div>
  
  <div class="col-md-2">
    <%= f.input :price_eu4, label: "EU4 Price" %>
  </div>

  <div class="col-md-2">
    <%= f.input :price_eu5, label: "EU5 Price" %>
  </div>
  
  <div class="col-md-2">
    <%= f.input :price_eu6, label: "EU6 Price" %>
  </div>
  </div>

  <div class="row">
  <div class="col-md-2">
    <%= f.input :price_usd, label: "USD1 Price" %>
  </div>

  <div class="col-md-2">
    <%= f.input :price_usd2, label: "USD2 Price" %>
  </div>
  
  <div class="col-md-2">
    <%= f.input :price_cny, label: "CNY Price" %>
  </div>
  </div>

  <% unless action_name == 'show' %>
  <div class="row">
    <div class="col-md-12">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  </div>
  <% end %>

<% end %>

app/views/prices/_new.html.erb
<%
   provide(:title, 'New Price Rule')
   provide(:button_text, 'Save New Rule')
%>

<div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <b class="modal-title" id="myModalLabel">New Price Rule</b>
</div>
<div class="modal-body">
       <%= render 'form' %>
</div>

<div class="modal-footer">
</div>

app/views/prices/_price.html.erb
  <tr>
        <td class='text-center'><%= price.scale_str %></td>
        <td class='text-center'><%= price.category_str %></td>
        <td class='text-center'><%= price.brand_str %></td>
        <td class='text-center'><%= to_currency price.price_eu %></td>
        <td class='text-center'><%= to_currency price.price_eu2 %></td>
        <td class='text-center'><%= to_currency price.price_eu3 %></td>
        <td class='text-center'><%= to_currency price.price_eu4 %></td>
        <td class='text-center'><%= to_currency price.price_eu5 %></td>
        <td class='text-center'><%= to_currency price.price_eu6 %></td>
        <td class='text-center'><%= to_currency price.price_usd, locale: :en %></td>
        <td class='text-center'><%= to_currency price.price_usd2, locale: :en %></td>
        <td class='text-center'><%= to_currency price.price_cny, locale: :cn %></td>
        <td class='text-center'><%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_price_path(price),
          remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %> 
        </td>
        <td class='text-center'><%= link_to '<i class="glyphicon glyphicon-remove-sign"></i>'.html_safe, price, method: :delete, 
          data: { confirm: "Are you sure you want to delete this price rule?" } %> 
        </td>
  </tr>

app/views/prices/_price_filter.html.erb
<%= simple_form_for :price, url: prices_path, method: :get do |f| %>
  <div class="row">
    <div class="col-md-1 pt-3"> 
      <b> Show only: </b>
    </div> 

    <div class="col-md-2">
      <%= f.input :scale, collection: SCALES, label: false, include_blank: 'All Scales', selected: @scale, input_html: { onchange: 'this.form.submit();'} %>
    </div>

    <div class="col-md-2">
    <%= f.input :brand, collection: BRANDS, label: false, include_blank: 'All Brands', selected: @brand, input_html: { onchange: 'this.form.submit();'} %>
    </div>

    <div class="col-md-2">
    <%= f.input :category, collection: CATEGORIES, label: false, include_blank: 'All Categories', selected: @category,  input_html: { onchange: 'this.form.submit();'}  %>
    </div>
  </div>
<% end %>

app/views/prices/create.html.erb
<h1>Prices#create</h1>
<p>Find me in app/views/prices/create.html.erb</p>

app/views/prices/edit.html.erb
<%
   provide(:button_text, 'Save changes')
%>
<div class="col-md-8 col-md-offset-2">
  <h3 class='display-1'><%= @price.brand_str %> <%= @price.scale_str %> <%= @price.category_str %> - Edit Price Rule</h3>
<div class="well">

       <%= render 'form' %>

</div>
</div>

app/views/prices/index.html.erb
<%= render "shared/modal" %>

<%= render 'price_filter' %>

<table class="table table-hover table-striped" >
  <caption>
    Products without matching rule will be ignored and their prices won't change. (See data integrity test for more details)
  </caption>
  <thead>
      <tr>
          <th class='text-center'>Scale</th>
          <th class='text-center'>Category</th>
          <th class='text-center'>Brand</th>
          <th class='text-center'>EU1 Price</th>
          <th class='text-center'>EU2 Price</th>
          <th class='text-center'>EU3 Price</th>
          <th class='text-center'>EU4 Price</th>
          <th class='text-center'>EU5 Price</th>
          <th class='text-center'>EU6 Price</th>
          <th class='text-center'>USD1 Price</th>
          <th class='text-center'>USD2 Price</th>
          <th class='text-center'>CNY Price</th>
          <th colspan=2></th>
      </tr>
  </thead>
  <tbody>

  <%= render @prices %>

  </tbody>
</table>

<p>&nbsp;</p>
<% notes = TableNote.find_by(table_name: 'prices').notes rescue '' %>
<div class="row">
<div class="col-md-12">
<div class="panel panel-info text-justify">
  <div class="panel-heading">Current Pricing Allocation Notes<span style="float: right"><%= link_to "<i class='glyphicon glyphicon-edit active'></i>".html_safe, edit_table_note_path(@table_note), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', method: :get %></span></div>
  <div class="panel-body" style="padding: 0;">
<pre ><%= notes.html_safe rescue '' %></pre>
</div>
</div>
</div>
</div>

  <div class="row">
    <div class="col-md-3">
    <%= button_to "Add New Price Rule", new_price_path, class: "btn btn-primary", remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', method: :get %>
    </div>
    <div class="col-md-3">
    <%= button_to "Apply Prices to All Products", apply_price_rules_to_products_path, class: "btn btn-warning mr-1", method: :post %>
    </div>

    <div class="col-md-4">
      <%= button_to "Apply Prices To All Orders", apply_price_rules_to_orders_path, class: "btn btn-danger mr-1", method: :post,  data: { confirm: "Are you sure you want to modify prices of all orders, including partially shipped orders? This might take a minite or two. Please do not interrupt"} %>
    </div>
  </div>

  <div class="p-4"></div>
   <p>* After changing existing or adding new prices, press "APPLY PRICE RULES" button. Otherwise prices won't change. </p>
   <p>** New prices will be applied only to products for which price rule exists in price matrix. The rest will be left unchanged. You can check for missing price rules with "Data Integrity Check" command accessible in top left sandwich menu. </p>
   <p>*** When you change prices of pending orders, all related documents, including POs and invoices, as well as order totals will change accordingly. Reports will be excluded from this operation and will reflect old prices/totals.

app/views/prices/new.html.erb
<%
   provide(:button_text, 'Save changes')
%>
<div class="col-md-8 col-md-offset-2">
<h3 class='display-1'>New Price Rule</h3>
<div class="well">

       <%= render 'form' %>

</div>
</div>

app/views/prices/show.html.erb
<h1>Prices#show</h1>
<p>Find me in app/views/prices/show.html.erb</p>

app/views/prices/update.html.erb
<h1>Prices#update</h1>
<p>Find me in app/views/prices/update.html.erb</p>