config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
#  root 'products#index'

# strange error appeared after upgrade to rails 6, hence this next line
  get '/active', to: proc { [200, {}, ['']] }

  devise_for :users, controllers: { registrations: "my_registrations" } 
  get '/users/', to: 'users#index'
  get '/switch_to/:id', to: 'users#switch_to', as: :switch_user
  get '/suppliers/index'
  get '/managers/index'
  get '/inventories', to: 'inventories#index'
  post '/update_stock/:id', to: 'products#update_stock', as:  :update_stock 
  post '/update_delta/:id', to: 'products#update_delta', as:  :update_delta 
  post '/apply_price_rules_to_products', to: 'products#apply_price_rules', as:  :apply_price_rules_to_products
  post '/apply_price_rules_to_orders', to: 'orders#apply_price_rules', as:  :apply_price_rules_to_orders
  get '/reports', to: 'reports#index'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  
  post '/add_product(/:id)', to: 'placements#add_product', as: :add_product
  get '/cart', to: 'placements#cart', as: :cart
  get '/empty_cart', to: 'placements#empty_cart', as: :empty_cart
  get '/delete_product(/:id)', to: 'placements#delete_product', as: :delete_product
  post '/update_product_qty(/:id)', to: 'placements#update_product_qty', as: :update_product_qty

  get '/image_upload', to: 'products#image_upload'
  post '/upload_image', to: 'products#upload_image'

  get '/self_test', to: 'self_test#index', as: :self_test

  resources :suppliers, :managers, :shippers, :users, :prices, :table_notes
  resources :products do
    get 'show_pending_orders', on: :member 
    get 'show_active_orders', on: :member 
#    post 'clear_active_order', on: :member
    post 'set_pending_orders_to_shipped', on: :member
    get 'disable', on: :member
    resources :ppos, only: [:index, :show, :create, :destroy] 
  end

# extra ppo paths  
  resources :ppos, only: [:index, :show, :create] do
    get 'show_placements', on: :member 
    post 'set_to_shipped', on: :member
    get 'export', on: :member
    get 'download', on: :member
  end

  resources :'packing_lists' do 
     get 'download', on: :member
     patch 'ship', on: :member
  end

  get '/inventory_template', to: 'products#inventory_template'
  get '/show_inventory', to: 'products#show_inventory'
  resources :inventories do
    get 'download', on: :member
  end

  get '/export_orders', to: 'orders#export' 
  get '/export_ppos', to: 'ppos#export' 

  resources :orders do
    get 'download_po', on: :member
    get 'download_invoice', on: :member
    get 'cancel', on: :member
    patch 'set_to_shipped', on: :member
    patch 'mark_as_paid', on: :member
  end

  resources :placements do
#      patch 'set_to_shipped', on: :member
#      get 'set_to_shipped', on: :member  # for redirect_to in placements#update_shipped
      patch 'update_shipped', on: :member
      get 'cancel', on: :member
   end

  resources :clients do
    get 'send_invite_to_register', on: :member
  end 

  resources :reports  do
     get 'download', on: :member
     get 'export', on: :member
  end

  resources :client_mails do
    get 'show_target', on: :member  # show target clients in client mailer
    get 'send_all', on: :member
    get 'send_staff', on: :member
  end

end

app/models/product.rb
class Product < ApplicationRecord

  include ApplicationHelper
  require 'csv'

  has_many :placements
  has_many :orders, through: :placements
  has_many :ppos
  has_many :clients

   mount_uploader :image, ImageUploader

  default_scope -> { order(ref_code: :asc, release_date: :asc) }

  scope :filter_by_title_or_refcode, lambda { |keyword|
    where("lower(description) LIKE '%#{keyword.downcase}%' OR lower(ref_code) LIKE '%#{keyword.downcase}%'" )
  }

  scope :above_or_equal_to_price, lambda { |price|
    where("price_eu >= ?", price)
  }

  scope :below_or_equal_to_price, lambda { |price|
    where("price_eu <= ?", price)
  }

  scope :recent, -> {
    order(:updated_at)
  }

  validates :ref_code, presence: true, length: { maximum: 10 }, uniqueness: true
  validates :description, :brand, :category, :scale,  presence: true
  validates :price_eu, :price_eu2, :price_usd,  numericality: { greater_than_or_equal_to: 0 }, presence: true
  validates :stock, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :delta, numericality: { only_integer: true }
  
  before_validation { description.strip!.gsub!(/\s+/,' ') rescue '' }
  before_validation { ref_code.gsub!(/\W+/,'') rescue '' }
  before_validation :set_prices!
  after_create :send_emails if SEND_EMAILS
  before_save :remove_blank_visible_tos, :set_active

# Notify staff, admins
  def send_emails
    UserMailer.new_product(self).deliver 
  end

  def set_prices!
    pr = Price.find_by(scale: self.scale, category: self.category)
    (errors.add(:price_eu, "Could not find price rule for this scale/category"); return; ) unless pr.present?
    self.price_eu = pr.price_eu
    self.price_eu2 = pr.price_eu2
    self.price_eu3 = pr.price_eu3
    self.price_eu4 = pr.price_eu4
    self.price_eu5 = pr.price_eu5
    self.price_eu6 = pr.price_eu6
    self.price_usd = pr.price_usd
    self.price_usd2 = pr.price_usd2
    self.delta ||= 0
  end

  def scale_str
    '1:'+scale.to_s
  end

  def brand_str
    BRANDS.invert[self.brand].to_s rescue nil
  end
  
  def progress_str
    self.progress ? "#{self.progress}%":'Unknown' rescue 'Unknown'
  end
  
  def active_str
    self.active? ? 'Yes':'No' rescue 'No'
  end
  
  def manual_price_str
    self.manual_price? ? 'Yes':'No' rescue 'No'
  end
  
  def category_str
    CATEGORIES.invert[self.category].to_s rescue nil
  end

  def colour_str
    COLOURS.invert[self.colour].to_s rescue nil
  end

  def supplier_str
    get_suppliers.invert[self.supplier]
  end

  def manager_str
    get_managers.invert[self.manager]
  end

  def release_date_str
    self.release_date.strftime("%m/%Y") rescue nil
  end
  
  def added_date_str
    self.added_date.strftime("%m/%Y") rescue self.created_at.strftime("%m/%Y")
  end

  def ref_code_and_descr
   "#{ref_code} : #{description}"
  end

  def image_file_present?
    File.exists?(self.image_path)
  end

  def image_path
    IMAGE_BASE.join(self.ref_code+'.jpg') rescue nil 
  end

  def normal_image_rel_path
    return "/images/#{self.ref_code}.jpg" if self.image_file_present?
    return "/images/dummy.jpg" 
  end

  def large_image_rel_path
    return "/images/400/#{self.ref_code}.jpg" if self.image_file_present?
    return "/images/400/dummy.jpg" 
  end
  
  def full_size_image_rel_path
    return "/images/fullsize/#{self.ref_code}.jpg" if self.image_file_present?
    return "/images/fullsize/dummy.jpg" 
  end

# Global method; search by keyword, price below, price above and recently added
  def self.search(keyword = '')
    products = Product.filter_by_title_or_refcode(keyword) if keyword
    products
  end
  
# Return pending orders for the product  
  def pending_order_placements
    self.placements.where(status: PENDING_ORDER)
  end

# Return placements marked as active order 
  def active_order_placements
    self.placements.where(status: ACTIVE_ORDER)
  end

# Return shipped orders for this product  
  def shipped_orders
    self.orders.where(status: SHIPPED_ORDER)
  end

# Return total number of this product in placements with given status
  def total_pcs(status = PENDING_ORDER)  
    self.placements.where(status: status).sum(:quantity) rescue 0
  end

  def pending_qty
    self.total_pcs
  end

# Number of active pieces  
  def active_qty 
    self.placements.where(status: ACTIVE_ORDER).sum('quantity-shipped')
  end

# Ordered quantity (pending+active)
  def quantity
    self.placements.sum('quantity-shipped')
  end

  def total_qty
    self.stock - self.delta - self.quantity
  end

# Number of shipped pieces  
  def shipped_qty 
    self.placements.sum(:shipped)
  end

# Last shipped PPO  
  def last_shipped_ppo
    Ppo.where(product_id:self.id).where(status: ARCHIVED_PPO).order('created_at desc').first rescue nil
  end

  def visible_to_str
    return 'All clients' unless self.clients.any?
    return "#{self.clients.count} clients"  
  end

  def visible_to_list
    return 'All' unless self.clients.any?
    self.clients.pluck(:name).join(', ') rescue 'All'
  end

  def visible?(client_id = nil)
    return unless client_id
    return true if self.visible_to.empty?
    return true if self.clients.exists?(client_id)
  end

  def remove_blank_visible_tos
    visible_to.reject!(&:blank?)
  end

  def set_active
    self.active = false unless self.image_file_present?
  end

  def pcs_available
    ''
  end 

# Generate QR code, return encoded string  
  def qr_code
    require 'barby'
    require 'barby/barcode'
    require 'barby/barcode/qr_code'
    require 'barby/outputter/png_outputter'
    url = "#{PROJECT_URL}/products/#{self.id}"
    qr = Barby::QrCode.new(url, level: :q, size: 5)
    base64_output = Base64.encode64(qr.to_png({ xdim: 2 }))
    return "data:image/png;base64,#{base64_output}"
  end

  def barcode
    require 'barby'
    require 'barby/barcode/code_128'
    require 'barby/outputter/png_outputter'
    barcode = Barby::Code128.new("#{self.id} : #{self.description}") rescue nil
    base64_output = Base64.encode64(barcode.to_png(:height => 35, :margin => 5)) if barcode
    return "data:image/png;base64,#{base64_output}" if base64_output.present?
  end

# Inventory CSV template  
  def self.to_csv
    attributes = %w{ref_code pcs_available description brand_str category_str colour_str scale_str notes }
    CSV.generate(headers: attributes, write_headers: true) do |csv|
      all.each do |product|
        csv << attributes.map{ |attr| product.send(attr) }
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  include My::Docs

  before_action :logged_in_user   # if this is enabled, message about activation email is not shown because of redirect
  before_action :admin_or_staff_user, only: [:new, :create, :edit, :update, :upload_image, :image_upload]
  before_action :admin_or_su_user, only: [:destroy]

  helper_method :sort_column, :sort_direction

  def new
    @product = Product.new
  end

  def index
      found = []
      @products = Product.all
      @products = Product.where(active: true) if (current_user.client? || current_user.user?)   # Do not show disabled products to clients and world
      if params[:findstr] 
        found = @products.search(params[:findstr])
        if found.any?
          @products = found
          flash.now[:info] = "Found #{@products.count} #{'product'.pluralize(@products.count)} matching string #{params[:findstr].inspect}"
        else
          flash.now[:info] = "No products found"
        end
      end
      if params[:sort] == 'pending'  # sorting on joined table
        @products = Product.joins(:placements).where('placements.status': PENDING_ORDER).group('id').reorder(Arel.sql('sum(quantity-shipped)' + ' ' + sort_direction)).paginate(page: params[:page])
      elsif params[:sort] == 'active' 
        @products = Product.joins(:placements).where('placements.status': ACTIVE_ORDER).group('id').reorder(Arel.sql('sum(quantity-shipped)'+ ' ' + sort_direction)).paginate(page: params[:page])
      else
        @products = @products.reorder(sort_column + ' ' + sort_direction).paginate(page: params[:page])
      end
  end

  def show
    @product = Product.find(params[:id]) rescue nil
    redirect_to products_path unless @product
    respond_to do |format|
      format.html #{ redirect_to products_path }  # Show only js version
      format.js
    end
  end

  def show_inventory
    if params[:findstr]
      @products = Product.search(params[:findstr]).paginate(page: params[:page])
      if @products.any?
        flash.now[:info] = "Found #{@products.count} #{'product'.pluralize(@products.count)} matching string #{params[:findstr].inspect}"
      else
        flash.now[:info] = "No products found"
      end
    else
      @products = Product.where(active: :true).reorder(sort_column + ' ' + sort_direction, "ref_code asc").paginate(page: params[:page])
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
       flash[:success] = "New product created"
       redirect_to products_path
    else
       render 'new'
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product deleted"
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.clients = []
    clients = params[:product][:'visible_to']
    clients = clients[1..] if clients.any?  # remove empty string
    clients.each do |cl|
      client_id = cl.to_i
      next unless client_id.positive?
      client = Client.find(cl.to_i)
      @product.clients.push(client) if client
    end
    if @product.update(product_params)
      suff = "; marked as inactive until picture is uploaded" unless @product.image_file_present?
      flash[:success] = "Product updated #{suff}"
      redirect_back(fallback_location: products_path)
    else
      render 'edit'
    end
  end

  def disable
    @product = Product.find(params[:id])
    if @product.update_attribute( :active, false )
      flash[:success] = "Product disabled - won't be visible by client"
      redirect_back(fallback_location: products_path)
    end
  end

  def update_stock
    @product = Product.find(params[:id])
    stock = params[:product][:stock].to_i.abs rescue 0
    if @product.update_attribute(:stock, stock)
       flash[:info] = "Product : #{@product.ref_code} - updated available stock"
    else 
       flash[:danger] = "Product : #{@product.ref_code} - error updating stock"
    end
    redirect_back(fallback_location: inventories_path)
  end

  def update_delta
    @product = Product.find(params[:id])
    delta = params[:product][:delta].to_i.abs rescue 0
    @product.update_attribute(:delta, delta)
    flash[:info] = "Product : #{@product.ref_code} - updated delta amount"
    redirect_back(fallback_location: inventories_path)
  end

  def apply_price_rules
    Price.all.each do |pr|
      Product.where(scale: pr.scale).where(category: pr.category).where(brand: pr.brand).where(manual_price: :false).
        update_all(price_eu: pr.price_eu, price_eu2: pr.price_eu2, price_eu3: pr.price_eu3, price_eu4: pr.price_eu4, 
                   price_eu5: pr.price_eu5, price_eu6: pr.price_eu6, price_usd: pr.price_usd, price_usd2: pr.price_usd2, price_cny: pr.price_cny)
    end
    flash[:success] = "Price rules applied to all products"
    redirect_back(fallback_location: prices_path)
  end

  def show_pending_orders
    @product = Product.find(params[:id])
    @placements = @product.pending_order_placements.paginate(page: params[:page])
    render 'inventories/show_pending_orders'
  end

  def show_active_orders
    @product = Product.find(params[:id])
    @placements = @product.active_order_placements.paginate(page: params[:page])
    render 'inventories/show_active_orders'
  end

  def set_pending_orders_to_shipped
    @product = Product.find(params[:id])
    @product.pending_order_placements.each do |pl|
      pl.set_to_shipped
    end
    flash[:info] = "#{@product.ref_code}: All pending placements marked as 'Shipped'"
    redirect_back(fallback_location: inventories_path)
  end

# post  
  def upload_image
    im = params[:image][:image] rescue nil
    fn = im.original_filename.upcase if im
    ref_code = Pathname(fn).basename('.JPG').to_s rescue nil

    @product = Product.find_by(ref_code: ref_code) if ref_code.present?
    if @product.present?
      @product.image = im
      if @product.save
        flash[:success] = "#{ref_code}: Image saved. Thumbnails created. Product updated"
      else
        flash.now[:danger] = @product.errors.full_messages.to_sentence
      end
    else
      flash[:warning] = "Product with Ref. code #{ref_code.inspect} does not exists. Please add it first"
    end
    redirect_to products_path
  end
  
# get: show form  
  def image_upload
    @product = Product.new
    render "upload"
  end

  # Generate inventory template in CSV
  def inventory_template
    @products = Product.where(active: true)
    respond_to do |format|
      format.html { redirect_to inventories_path }
      format.csv { send_data @products.to_csv, filename: "inventory_#{Time.now.strftime("%d_%m_%Y")}.csv" }
    end
    flash.now[:info] = "Inventory template generated. Contains #{@products.count} products"
  end

private
  def product_params
    params.require(:product).permit( :ref_code, :description, :brand, :category, :scale, :colour, :ctns, :release_date, :added_date, 
                                     :weight, :active, :price_eu, :price_eu2, :price_eu3, :price_eu4, :price_eu5, :price_eu6, 
                                     :price_usd, :price_usd2, :price_cny,  :supplier, :manager, :progress, :manual_price,  :notes, :image,
                                     :stock, :delta, visible_to: [] ) 
  end

  def sort_column
          Product.column_names.include?(params[:sort]) ? params[:sort] : "ref_code"
  end

  def sort_direction
          %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end

app/helpers/products_helper.rb
module ProductsHelper

  def product_editable?
    current_user && (current_user.admin? || current_user.staff?)
  end
end

app/views/products/_admin_product.html.erb
<td class="text-center"><%= to_currency(product.price_eu) %></td>
<td class="text-center"><%= product.supplier_str %></td>

<td class="text-center">
  <%= link_to "#{product.pending_qty}", show_pending_orders_product_path(product),
            remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
</td>
<td class="text-center">
  <%= link_to "#{product.active_qty}", show_active_orders_product_path(product),
            remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
</td>   

<td class="text-center"><%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_product_path(product), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %> </td>
<td class="text-center">
<% unless product.orders.any? %>
<%= link_to '<i class="glyphicon glyphicon-remove-sign"></i>'.html_safe, product, method: :delete, data: { confirm: "Are you sure you want to delete #{product.ref_code}?" } %>
<% end %>
</td>

app/views/products/_edit.html.erb
<%
   provide(:title, 'Edit Product')
   provide(:button_text, 'Save changes')
%>

<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <b class="modal-title" id="myModalLabel"><%= "#{@product.ref_code} : #{@product.description}" %> - Edit Product</b>
</div>
<div class="modal-body">
       <%= render 'form' %>
</div>

<div class="modal-footer">
</div>

app/views/products/_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <% readonly = (action_name == 'new')? false: true %>

  <div class="row" %>
  <div class="col-md-2">
  <%= f.input :ref_code, hint: "Unique product code", readonly: readonly %>
  </div>
  <div class="col-md-2">
  <%= f.input :brand, collection: BRANDS, include_blank: false %> 
  </div>
  <div class="col-md-2">
  <%= f.input :category, collection: CATEGORIES, include_blank: false %>
  </div>
  <div class="col-md-2">
  <%= f.input :colour, collection: COLOURS  %>
  </div>
  <div class="col-md-2">
  <%= f.input :ctns, label: 'Pcs x Cartons' %>
  </div>
  <div class="col-md-2">
  <%= f.input :scale  %>
  </div>
  </div>

  <div class="row" %>
  <div class="col-md-12">
  <%= f.input :description %>
  </div>
  </div>

  <div class="row" %>
  <div class="col-md-2">
  <%= f.input :weight, label: 'Weight (G)' %>
  </div>
  <div class="col-md-3">
  <%= f.input :added_date, as: :date, html5: true  %>
  </div>
  <div class="col-md-3">
  <%= f.input :release_date, as: :date,  html5: true  %>
  </div>
  <div class="col-md-2">
  <%= f.input :manual_price, collection: [['Yes', 'true'], ['No', 'false']], value: 'true', include_blank: false %>
  </div>
  <div class="col-md-2">
  <%= f.input :active, collection: [['Yes', 'true'], ['No', 'false']], value: 'true', include_blank: false %>
  </div>
  </div>

  <div class="row" %>
  <div class="col-md-3">
  <%= f.input :manager, collection: get_managers, include_blank: 'unknown'  %>
  </div>
  <div class="col-md-3">
  <%= f.input :supplier, collection: get_suppliers,  include_blank: 'unknown' %>
  </div>
  <div class="col-md-2">
  <%= f.input :progress, label: '% Complete' %>
  </div>
  <div class="col-md-4">
    <%= f.input :visible_to, collection: Client.all, label: "Visible to: #{@product.visible_to_list}", include_blank: 'ALL', selected: @product.visible_to, input_html: {multiple: true, size: 5}, hint: "Use Command/Alt key to select multiple values" %>
  </div>
  </div>

  <%= f.input :notes, as: :text %>
  <% unless action_name == 'show' %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

<% end %>


<script>
$(document).ready(function() {
  var manual_price = $("#edit_product_<%=@product.id%> select[name='product[manual_price]']");
  var eu = document.getElementById("product_price_eu");
  var eu2 = document.getElementById("product_price_eu2");
  var eu3 = document.getElementById("product_price_eu3");
  var eu4 = document.getElementById("product_price_eu4");
  var eu5 = document.getElementById("product_price_eu5");
  var eu6 = document.getElementById("product_price_eu6");
  var usd = document.getElementById("product_price_usd");
  var usd2 = document.getElementById("product_price_usd2");

  if (manual_price.val() == 'true') { 
    eu.style.backgroundColor = 'yellow';
    eu2.style.backgroundColor = 'yellow';
    eu3.style.backgroundColor = 'yellow';
    eu4.style.backgroundColor = 'yellow';
    eu5.style.backgroundColor = 'yellow';
    eu6.style.backgroundColor = 'yellow';
    usd.style.backgroundColor = 'yellow';
    usd2.style.backgroundColor = 'yellow';
  }
}
);

</script>

app/views/products/_new.html.erb
<%
   provide(:title, 'Create New Product')
   provide(:button_text, 'Save New Product')
%>

<div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <b class="modal-title" id="myModalLabel">Create New Product</b>
</div>
<div class="modal-body">
       <%= render 'form' %>
</div>

<div class="modal-footer">
</div>

app/views/products/_product.html.erb
<% cl = nil %>
<% return if current_user.client? && !product.visible?(current_user.client_id) %>
<% if current_user.client? %>
   <% cl = 'table-success' if in_cart?(product.id)  %>
<% elsif current_user.staff? || current_user.admin? || current_user.su? %>
   <% cl = 'table-warning' unless product.active? %>
   <% cl = 'table-danger' if product.manual_price? %>
<% end %>

  <tr class="<%= cl %>">
    <td class="text-center">
    <% if device_is_desktop? %>
      <%= link_to product.ref_code, product, remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window', class: cl %>
    <% else %>
      <%= link_to product.ref_code, product %>
    <% end %>

    <td class="text-center"><%= product.scale_str %></td> 
    <td class="text-center"><%= product.colour_str %></td> 
    <td class="text-center"><%= product.weight.to_i %></td> 
    <td><%= product.description %></td>
    <td class="text-center"><%= product.category_str %></td> 
    <td class="text-center"><%= product.brand_str %></td> 
    <td class="text-center"><%= product.ctns %></td> 
    <td class="text-center"><%= product.release_date_str %></td>
    <%= render("#{current_user.role}_product", product: product) if current_user %>
</tr>

app/views/products/_production_product.html.erb
<td class="text-center"><%= product.supplier_str %></td>
<td class="text-center">
  <%= link_to "#{product.pending_qty}", show_pending_orders_product_path(product),
            remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
</td>
<td class="text-center">
  <%= link_to "#{product.active_qty}", show_active_orders_product_path(product),
            remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
</td>

app/views/products/_staff_index.html.erb
<th class="tbl_sm, text-center"><%= sortable 'price_eu', 'Price EU' %></th>
<th class="tbl_md, text-center">Supplier</th>
<th class="tbl_md, text-center"><%= sortable 'pending', 'Pending' %></th>
<th class="tbl_md, text-center"><%= sortable 'active', 'Active' %></th>
<th></th>
<th></th>

app/views/products/_su_product.html.erb
<td class="text-center"><%= to_currency(product.price_eu) %></td>
<td class="text-center"><%= product.supplier_str %></td>
<td class="text-center">
  <%= link_to "#{product.pending_qty}", show_pending_orders_product_path(product), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
</td>
<td class="text-center">
  <%= link_to "#{product.active_qty}", show_active_orders_product_path(product), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
</td>
<td class="text-center"><%= link_to '<i class="glyphicon glyphicon-edit"></i>'.html_safe, edit_product_path(product), remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %> </td>
<td class="text-center"><%= link_to '<i class="glyphicon glyphicon-remove-sign"></i>'.html_safe, product, method: :delete, data: { confirm: "Are you sure you want to delete #{product.ref_code}?" } %> </td>

app/views/products/_upload_form.html.erb
<h4>Product image upload</h4>
<div class="well">

  <h5> Please provide full resolution image named [Ref. Code].jpg </h5>
  <%= simple_form_for @product, url: upload_image_path, html: {multipart: false, class: "dropzone", id:"my-dropzone"}, method: :post do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  
<div id='dropzone_panel'>
  <div class="dz-message">Drop jpg file here to upload</div>
  <%= f.hint 'If image exists on the server, it will be replaced. Current size limit is 5Mb' %>
</div>
</form>
</div>
<%= f.button :submit, "Upload", class:"btn btn-block btn-primary", id: "submit", disabled: true %>
<% end %>

<script>
Dropzone.options.myDropzone = {
  paramName: "image[image]",
  acceptedFiles: ".jpg,.JPG ",
  maxFiles: 1,
  maxFilesize: 5, // MB
  addRemoveLinks: true,
  url: "<%= upload_image_url %>",
  autoDiscover: false,
  uploadMultiple: false,
  autoProcessQueue: false,
  parallelUploads: 20,
  timeout: 60000,
//  autoQueue: false,

init: function() {
//    this.on("addedfile", function() { if (this.files[1]!=null){ this.removeFile(this.files[0]); } });
    this.on("success", function(file) { window.location = "<%= products_path %>"; });
    this.on("error", function (msg) { alert(msg.responseText); });
    this.on("queuecomplete", function () { alert("Upload successful"); });
    var submitButton = document.querySelector("#submit");
    myDropzone = this; // closure

    submitButton.addEventListener("click", function() {
      myDropzone.processQueue(); // Tell Dropzone to process all queued files.
    });

    this.on("addedfile", function(file) {
      var submit = document.getElementById('submit');
//    console.log("loaded");
      submit.disabled = false;
    });
}
};
  
</script>