config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
#  root 'products#index'

# strange error appeared after upgrade to rails 6, hence this next line
  get '/active', to: proc { [200, {}, ['']] }

  devise_for :users, controllers: { registrations: "my_registrations" } 
  get '/users/', to: 'users#index'
  get '/switch_to/:id', to: 'users#switch_to', as: :switch_user
  get '/suppliers/index'
  get '/managers/index'
  get '/inventories', to: 'inventories#index'
  post '/update_stock/:id', to: 'products#update_stock', as:  :update_stock 
  post '/update_delta/:id', to: 'products#update_delta', as:  :update_delta 
  post '/apply_price_rules_to_products', to: 'products#apply_price_rules', as:  :apply_price_rules_to_products
  post '/apply_price_rules_to_orders', to: 'orders#apply_price_rules', as:  :apply_price_rules_to_orders
  get '/reports', to: 'reports#index'

  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'
  get '/terms', to: 'static_pages#terms'
  get '/privacy', to: 'static_pages#privacy'
  
  post '/add_product(/:id)', to: 'placements#add_product', as: :add_product
  get '/cart', to: 'placements#cart', as: :cart
  get '/empty_cart', to: 'placements#empty_cart', as: :empty_cart
  get '/delete_product(/:id)', to: 'placements#delete_product', as: :delete_product
  post '/update_product_qty(/:id)', to: 'placements#update_product_qty', as: :update_product_qty

  get '/image_upload', to: 'products#image_upload'
  post '/upload_image', to: 'products#upload_image'

  get '/self_test', to: 'self_test#index', as: :self_test

  resources :suppliers, :managers, :shippers, :users, :prices, :table_notes
  resources :products do
    get 'show_pending_orders', on: :member 
    get 'show_active_orders', on: :member 
#    post 'clear_active_order', on: :member
    post 'set_pending_orders_to_shipped', on: :member
    get 'disable', on: :member
    resources :ppos, only: [:index, :show, :create, :destroy] 
  end

# extra ppo paths  
  resources :ppos, only: [:index, :show, :create] do
    get 'show_placements', on: :member 
    post 'set_to_shipped', on: :member
    get 'export', on: :member
    get 'download', on: :member
  end

  resources :'packing_lists' do 
     get 'download', on: :member
     patch 'ship', on: :member
  end

  get '/inventory_template', to: 'products#inventory_template'
  get '/show_inventory', to: 'products#show_inventory'
  resources :inventories do
    get 'download', on: :member
  end

  get '/export_orders', to: 'orders#export' 
  get '/export_ppos', to: 'ppos#export' 

  resources :orders do
    get 'download_po', on: :member
    get 'download_invoice', on: :member
    get 'cancel', on: :member
    patch 'set_to_shipped', on: :member
    patch 'mark_as_paid', on: :member
  end

  resources :placements do
#      patch 'set_to_shipped', on: :member
#      get 'set_to_shipped', on: :member  # for redirect_to in placements#update_shipped
      patch 'update_shipped', on: :member
      get 'cancel', on: :member
   end

  resources :clients do
    get 'send_invite_to_register', on: :member
  end 

  resources :reports  do
     get 'download', on: :member
     get 'export', on: :member
  end

  resources :client_mails do
    get 'show_target', on: :member  # show target clients in client mailer
    get 'send_all', on: :member
    get 'send_staff', on: :member
  end

end

app/models/report.rb
class Report < ApplicationRecord
        default_scope -> { order(id: :desc) }
        attr_accessor :client, :filespec
#  belongs_to :client, inverse_of: :reports
  
        before_validation :set_attributes!

        validates :name, :filename, presence: true, length: { maximum: 30 }
        validates :timeframe, :client_id, :detail,  numericality: { only_integer: true }, allow_blank: true
#        validates :sdate, presence: true, if: Proc.new { |a| a.timeframe == DAY_REPORT || a.timeframe == DRANGE_REPORT }
#        validates :edate, presence: true, if: Proc.new { |a| a.timeframe == DRANGE_REPORT}
##        validates :product_id, presence: true, if: Proc.new { |p| p.category == PRODUCT_REPORT}

  def set_attributes!
    nextid = Report.maximum(:id).next rescue 1
    self.name = "#{Date.today}-#{nextid}"
    "#{self.product.ref_code}-" << self.name if self.product_id
    self.filename = self.name+'.pdf'
    self.detail ||= TOTALS_ONLY_REPORT
    old_report = Report.find_by(filename: self.filename)
    if old_report.present?
       File.delete( old_report.filespec ) rescue nil
       old_report.destroy
    end
  end 

  def client
    Client.find(self.client_id) rescue nil
  end

  def product
    Product.find(self.product_id) rescue nil
  end
  
  def client_code
    self.client.code rescue 'All'
  end

  def filespec
    REPORTS_PATH.join(filename) rescue nil
  end

  def exists?
    File.exists?(self.filespec) rescue false
  end

  def filesize
    sprintf("%.2f", File.size(self.filespec).to_f/2**20) rescue 0
  end

  def status_str
    ORDER_STATUSES.invert[self.status] || 'All'
  end

  def category_str
    REPORT_CATEGORIES.invert[self.category] || 1
  end

# Class method  
  def self.cat_str(category)
    REPORT_CATEGORIES.invert[category] || 1
  end
  
  def timeframe_str
    REPORT_TIMEFRAMES.invert[self.timeframe] || 'All Time'
  end

  def detail_str
    REPORT_DETAILS.invert[self.detail]
  end

  def daterange 
    return '' unless self.sdate
    if self.timeframe == DAY_REPORT 
      return self.sdate.to_date
    else
      return "#{self.sdate.to_date} - #{self.edate.to_date}" 
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  include My::Docs
  require 'fileutils'

  before_action :logged_in_user
  before_action :admin_or_staff_user
  before_action :admin_or_staff_user, only: [:destroy]

  helper_method :sort_column, :sort_direction

  def index
    @category = params[:category].to_i || 1
    @reports = Report.where(category: @category)
    @reports = @reports.where(geo: GEO_CN) if current_user.production?
    @reports = @reports.where(client_id: current_user.client_id) if current_user.client?
    @reports = @reports.reorder(sort_column + ' ' + sort_direction, "created_at desc").paginate(page: params[:page])
    flash.now[:warning] = 'No reports found' unless @reports.any?
  end

  def new
    @report = Report.new(category: params[:category])
    @report.geo = client_geo
  end

  def create
    @report = Report.new(report_params)
    @report.sdate ||= Date.today
    @report.edate ||= Date.today
    year = params[:date][:year] || Date.today.year
    month  = params[:date][:month] || Date.today.month
    
    case @report.timeframe
        when 1   # Day
          @report.edate = @report.sdate + 24.hours rescue Time.now
        when 2   # Week
          @report.edate = @report.sdate + 1.week - 1.minute 
        when 3   # Month
          @report.sdate = Date.new(year.to_i,month.to_i) 
          @report.edate = @report.sdate + 1.month - 1.minute
        when 4   # Quarter to Date
          @report.sdate = Date.today.beginning_of_quarter 
          @report.edate = Time.now 
        when 5   # Year
          @report.sdate = Date.new(year.to_i,1,1) 
          edate = @report.sdate + 1.year
          @report.edate =  [edate, Date.today].min
        when 6   # Date Range
          @report.edate = [report.edate,Date.today].min
        when nil # All Time
          @report.sdate = Order.minimum(:created_at)
          @report.edate = Time.now 
        else     # invalid
          flash.now[:danger] = "Invalid report timeframe: #{@report.timeframe}"
        end

       if flash[:danger]
          redirect_back(fallback_location: reports_path)
       elsif @report.save
         flash.now[:info] = @report.inspect
          redirect_to export_report_path(@report, category: params[:category] )
       else
          flash.now[:danger] = @report.errors.full_messages.to_sentence
          render 'new'
       end
  end

  def destroy
    @report = Report.find(params[:id])
    if @report.present?
      File.delete( @report.filespec ) rescue nil
      @report.destroy
      flash[:success] = "Report deleted"
    end

    redirect_back(fallback_location: reports_path, page: params[:page])
  end

  def download
   @report = Report.find( params[:id] )

   if @report.exists?
          send_file @report.filespec,
             filename: @report.filename,
             type: "application/pdf",
             disposition: :attachment
   else
     flash.now[:danger] = "File #{@report.filename} was not found - regenerating"
     redirect_to export_report_path(@report)
   end
  end

# Generate PDF,CSV versions of the report, save in reports directory
  def export
    @report = Report.find(params[:id])
    @orders = get_orders( @report )
    if @orders.any?
      respond_to do |format|
        format.html { @pdf = build_report( @report, @orders )
                      @pdf.render_file @report.filespec
                      redirect_to reports_path(category: @report.category) 
                    }
        format.csv { send_data @orders.to_csv(detail = @report.detail), filename: "#{@report.name}.csv" }
      end
      flash.now[:info] = "New report created. Contains #{@orders.count} orders "
    else
      @report.destroy
      flash[:danger] = "No report created. No orders were found matching given criteria"
      redirect_to reports_path(category: @report.category) 
    end
  end

  def show
    @report = Report.find(params[:id])
    (redirect_to reports_path; return) unless @report

    respond_to do |format|
      format.html {
        send_file(@report.filespec,
             filename: @report.filename,
             type: "application/pdf",
             disposition: :inline)
      }
      format.js
    end
  end

private
  def report_params
    params.require(:report).permit(:name, :filename, :status, :category, :client_id, :product_id, :sdate, :edate, :timeframe, :detail, :geo)
  end

  def sort_column
    Report.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

# Get orders/placements in given timeframe matching given client/status 
  def get_orders(report)
    case report.category
      when CLIENT_REPORT
      orders = Order.all
      orders = orders.where(geo: GEO_CN) if current_user.production?
      orders = orders.where(client_id: report.client_id) if report.client_id
      orders = orders.where(created_at: (report.sdate..report.edate))
      orders = orders.where(status: report.status) if report.status.present?
      return orders
    when PRODUCT_REPORT
      placements = Placement.where(created_at: (report.sdate..report.edate))
      placements = placements.where(product_id: report.product_id) if report.product_id
      placements = placements.where(status: report.status) if report.status.present?
      placements = placements.joins(:order).where('orders.geo': GEO_CN) if current_user.production?
      placements = placements.joins(:order).where('orders.client_id': report.client_id) if report.client_id
      return placements
    when SUMMARY_REPORT
#p= Placement.joins(:order).where("orders.client_id":405).group(:product_id).pluck(:product_id,'sum(quantity)','sum(shipped)','sum(to_ship)','count(order_id)','sum(price)')
      placements = Placement.where(created_at: (report.sdate..report.edate))
      placements = placements.where(status: report.status) if report.status.present?
      placements = placements.joins(:order).where('orders.geo': GEO_CN) if current_user.production?
      placements = placements.joins(:order).where('orders.client_id': report.client_id) if report.client_id
      return placements
    else 
#      logger.error "*** Invalid Report Category: #{report.inspect}"
#       redirect_to reports_path
       return []
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_client_index.html.erb
<% if @reports.any? %>
<table class="table table-hover table-striped">
  <caption>List of Client Reports</caption>
   <thead>
      <tr>
          <th class="text-center">Id</th>
          <th>Client</th>
          <th>Type</th>
          <th>Time Frame</th>
          <th>Date Range</th>
          <th>Detail</th>
          <th>Created on</th> 
          <th></th>
          <th></th>
          <% unless current_user.client? %>
            <th></th>
          <% end %>
      </tr>
  </thead>
  <tbody>

  <%= render @reports %>

  </tbody>
</table>

<div class="bottom_nav">
<%= will_paginate @reports, class: "btn" %>
</div>

<% end %>

app/views/reports/_form.html.erb
  
<%= simple_form_for @report do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.input :category, as: :hidden %>
  <div class="row" %>
   <div class="col-md-6">
       <%= f.input :client_id, collection: get_clients_with_orders, include_blank: 'All' %> 
   </div>
   <div class="col-md-6">
      <%= f.input :status, collection: ORDER_STATUSES, label: "Order Status ", include_blank: false  %>
    </div>

  </div>

  <div class="row" >
    <div class="col-md-6">
       <%= f.input :timeframe, collection: REPORT_TIMEFRAMES, include_blank: 'All Time' %>
    </div>
    <div class="col-md-6">
      <%= f.input :detail, collection: REPORT_DETAILS, label: "Report Detail",  include_blank: false %> 
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id='sdate' style="display:none;">
      <%= f.input :sdate, as: :date, label: 'Start Date', html5: true  %>
    </div>
    <div class="col-md-6" id="edate" style="display:none;">
      <%= f.input :edate, as: :date, label: 'To Date', html5: true  %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id="year" style="display:none;">
       <%= f.label "Year" %>
       <%= select_year Time.now, {start_year: Time.now.year-10, end_year: Time.now.year}, class: "form-control" %>
    </div>
    <div class="col-md-6" id="month" style="display:none;">
       <%= f.label "Month" %>
       <%= select_month Time.now, {}, class: "form-control" %>
    </div>
  </div>

  <p>&nbsp; </p>
  <% unless action_name == 'show' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

<% end %>

<script>
$(document).ready(function () {

    $('#new_report select[name="report[timeframe]"]').change(function () {
        switch ( $('#new_report select[name="report[timeframe]"]').val() ) {
                case "1":               // Daily
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "2":               // Week 
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "3":               // Month
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').show();
                        break;
                case "4":               // Quarter 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "5":               // Year 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').hide();
                        break;
                case "6":               // Date Range 
                        $('#sdate').show();
                        $('#edate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;

                }

    });
});

</script>

app/views/reports/_form1.html.erb
<% disabled = current_user.client? %>
<%= simple_form_for @report do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.hidden_field :client_id, value: current_user.client_id %>
  <%= f.hidden_field :geo, value: @report.geo %>

  <%= f.input :category, as: :hidden %>

  <div class="row" %>
   <div class="col-md-6">
       <%= f.input :client_id, collection: get_clients_with_orders(@report.geo), include_blank: 'All', selected: current_user.client_id, disabled: disabled %> 
   </div>
   <div class="col-md-6">
      <%= f.input :status, collection: ORDER_STATUSES, label: "Order Status ", include_blank: 'All'  %>
    </div>
  </div>

  <div class="row" >
    <div class="col-md-6">
       <%= f.input :timeframe, collection: REPORT_TIMEFRAMES, include_blank: 'All Time' %>
    </div>
    <div class="col-md-6">
      <%= f.input :detail, collection: REPORT_DETAILS, label: "Report Detail",  include_blank: false %> 
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id='sdate' style="display:none;">
      <%= f.input :sdate, as: :date, label: 'Start Date', html5: true  %>
    </div>
    <div class="col-md-6" id="edate" style="display:none;">
      <%= f.input :edate, as: :date, label: 'To Date', html5: true  %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id="year" style="display:none;">
       <%= f.label "Year" %>
       <%= select_year Time.now, {start_year: Time.now.year-10, end_year: Time.now.year}, class: "form-control" %>
    </div>
    <div class="col-md-6" id="month" style="display:none;">
       <%= f.label "Month" %>
       <%= select_month Time.now, {}, class: "form-control" %>
    </div>
  </div>

  <p>&nbsp; </p>
  <% unless action_name == 'show' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

<% end %>

<script>
$(document).ready(function () {

    $('#new_report select[name="report[timeframe]"]').change(function () {
        switch ( $('#new_report select[name="report[timeframe]"]').val() ) {
                case "1":               // Daily
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "2":               // Week 
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "3":               // Month
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').show();
                        break;
                case "4":               // Quarter 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "5":               // Year 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').hide();
                        break;
                case "6":               // Date Range 
                        $('#sdate').show();
                        $('#edate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;

                }

    });
});

</script>

app/views/reports/_form2.html.erb
<% disabled = current_user.client? %>
<%= simple_form_for @report do |f| %>
  <%= f.hidden_field :client_id, value: current_user.client_id %>
  <%= f.hidden_field :geo, value: @report.geo %>

  <%= f.input :category, as: :hidden %>
  <div class="row" %>
   <div class="col-md-6">
       <%= f.input :product_id, collection: Product.all, value_method: :id, label_method: :ref_code_and_descr, include_blank: 'All' %> 
   </div>
   <div class="col-md-6">
       <%= f.input :client_id, collection: get_clients_with_orders(@report.geo), include_blank: 'All', selected: current_user.client_id, disabled: disabled %>
   </div>
  </div>
  <div class="row" %>
   <div class="col-md-6">
      <%= f.input :status, collection: ORDER_STATUSES, label: "Order Status ", include_blank: 'All'  %>
    </div>
    <div class="col-md-6">
       <%= f.input :timeframe, collection: REPORT_TIMEFRAMES, include_blank: 'All Time' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id='sdate' style="display:none;">
      <%= f.input :sdate, as: :date, label: 'Date', html5: true  %>
    </div>
    <div class="col-md-6" id="edate" style="display:none;">
      <%= f.input :edate, as: :date, label: 'To Date', html5: true  %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id="year" style="display:none;">
       <%= f.label "Year" %>
       <%= select_year Time.now, {start_year: Time.now.year-10, end_year: Time.now.year}, class: "form-control" %>
    </div>
    <div class="col-md-6" id="month" style="display:none;">
       <%= f.label "Month" %>
       <%= select_month Time.now, {}, class: "form-control" %>
    </div>
  </div>

  <p>&nbsp; </p>
  <% unless action_name == 'show' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

<% end %>


<script>
$(document).ready(function () {
  
    $.fn.select2.defaults.set( "theme", "classic" );
    $("#report_product_id").select2();

    $('#new_report select[name="report[timeframe]"]').change(function () {
        switch ( $('#new_report select[name="report[timeframe]"]').val() ) {
                case "1":               // Daily
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "2":               // Week 
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "3":               // Month
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').show();
                        break;
                case "4":               // Quarter 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "5":               // Year 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').hide();
                        break;
                case "6":               // Date Range 
                        $('#sdate').show();
                        $('#edate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;

                }

    });
});

</script>

app/views/reports/_form3.html.erb
<% disabled = current_user.client? %>
<%= simple_form_for @report do |f| %>
  <%= f.hidden_field :client_id, value: current_user.client_id %>
  <%= f.hidden_field :geo, value: @report.geo %>
  <%= f.hidden_field :category %>

  <div class="row" %>
   <div class="col-md-4">
       <%= f.input :client_id, collection: get_clients_with_orders(@report.geo), include_blank: 'All', selected: current_user.client_id, disabled: disabled %>
   </div>
   <div class="col-md-4">
      <%= f.input :status, collection: ORDER_STATUSES, label: "Order Status ", include_blank: 'All'  %>
    </div>
    <div class="col-md-4">
       <%= f.input :timeframe, collection: REPORT_TIMEFRAMES, include_blank: 'All Time' %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id='sdate' style="display:none;">
      <%= f.input :sdate, as: :date, label: 'Date', html5: true  %>
    </div>
    <div class="col-md-6" id="edate" style="display:none;">
      <%= f.input :edate, as: :date, label: 'To Date', html5: true  %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6" id="year" style="display:none;">
       <%= f.label "Year" %>
       <%= select_year Time.now, {start_year: Time.now.year-10, end_year: Time.now.year}, class: "form-control" %>
    </div>
    <div class="col-md-6" id="month" style="display:none;">
       <%= f.label "Month" %>
       <%= select_month Time.now, {}, class: "form-control" %>
    </div>
  </div>

  <p>&nbsp; </p>
  <% unless action_name == 'show' %>
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
  <% end %>

<% end %>


<script>
$(document).ready(function () {
  
    $.fn.select2.defaults.set( "theme", "classic" );
    $("#report_product_id").select2();

    $('#new_report select[name="report[timeframe]"]').change(function () {
        switch ( $('#new_report select[name="report[timeframe]"]').val() ) {
                case "1":               // Daily
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "2":               // Week 
                        $('#edate').hide();
                        $('#sdate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "3":               // Month
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').show();
                        break;
                case "4":               // Quarter 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').hide();
                        $('#month').hide();
                        break;
                case "5":               // Year 
                        $('#sdate').hide();
                        $('#edate').hide();
                        $('#year').show();
                        $('#month').hide();
                        break;
                case "6":               // Date Range 
                        $('#sdate').show();
                        $('#edate').show();
                        $('#year').hide();
                        $('#month').hide();
                        break;

                }

    });
});

</script>

app/views/reports/_product_index.html.erb
<% if @reports.any? %>
<table class="table table-hover table-striped">
  <caption>List of Product Reports</caption>
   <thead>
      <tr>
          <th class="text-center">Id</th>
          <th>Product</th>
          <th>Client</th>
          <th>Type</th>
          <th>Time Frame</th>
          <th>Date Range</th>
          <th>Detail</th>
          <th>Created on</th> 
          <th></th>
          <th></th>
          <% unless current_user.client? %>
            <th></th>
          <% end %>
      </tr>
  </thead>
  <tbody>

  <%= render @reports %>

  </tbody>
</table>

<div class="bottom_nav">
<%= will_paginate @reports, class: "btn" %>
</div>

<% end %>

app/views/reports/_report.html.erb
<tr>
  <td class="text-center">
  <% if report.exists? %>
     <%= link_to report.id, report, remote: true, 'data-toggle':  "modal", 'data-target': '#modal-window' %>
  <% else %>
     <%= report.id %>
  <% end %>
  </td>

  <% if report.category == PRODUCT_REPORT %>
  <td><%= report.product.ref_code rescue 'All' %></td>
  <% end %>
  <td><%= report.client_code %></td>
  <td><%= report.status_str %></td>
  <td><%= report.timeframe_str %></td>
  <td><%= report.daterange %></td>
  <td><%= report.detail_str %></td>
  <td><%= report.created_at %></td>
  <% if report.exists? %>
        <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-download"></i>'.html_safe, download_report_path(report)  %></td>
  <% else %> <!-- regenerate report -->
        <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-question-sign"></i>'.html_safe, download_report_path(report)  %></td>
  <% end %>

    <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-export"></i>'.html_safe, export_report_path(report, format: :csv) %></td>
  <% unless current_user.client?%>
    <td class="text-center"><%= link_to '<i class="glyphicon glyphicon-remove-sign"></i>'.html_safe, report, method: :delete, data: { confirm: "Are you sure you want to delete report '#{report.name}'?" } %> </td>
  <% end %>
 </tr>

app/views/reports/_show.html.erb
<%
   provide(:title, "Show Report")
%>

<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <b class="modal-title" id="myModalLabel"><%= @report.category_str %> Report <%= @report.name %></b>
</div>
<div class="modal-body">
        <iframe id="myModal" src="/reports/<%= @report.id %>" frameborder="0" width="100%" height="600px"></iframe>
</div>

app/views/reports/_summary_index.html.erb
<% if @reports.any? %>
<table class="table table-hover table-striped">
  <caption>List of Summary Reports</caption>
   <thead>
      <tr>
          <th class="text-center tbl_sm">Id</th>
          <th>Client</th>
          <th>Type</th>
          <th>Time Frame</th>
          <th class="tbl_lmd">Date Range</th>
          <th>Detail</th>
          <th class='tbl_lmd'>Created on</th> 
          <th class="tbl_sm"></th>
          <th class="tbl_sm"></th>
      </tr>
  </thead>
  <tbody>

  <%= render @reports %>

  </tbody>
</table>

<div class="bottom_nav">
<%= will_paginate @reports, class: "btn" %>
</div>

<% end %>

app/views/reports/index.html.erb
<% provide(:title, 'Reports') %>
<%= render "shared/modal" %>

<% cat_str = Report.cat_str(@category).downcase rescue 'product' %>
<%= render "#{cat_str}_index" %>

<div class="bottom_buttons">
  <%= link_to "Create #{cat_str} report ", new_report_path(category: @category), class: "btn btn-primary col-md-2 ", method: 'get'  %>
</div>

<script>
$zoho.salesiq.ready=function(embedinfo)
{ $zoho.salesiq.floatbutton.visible("hide"); }
</script>

app/views/reports/new.html.erb
<%
   provide(:button_text, 'Create New Report')
%>

<div class="col-md-8 col-md-offset-2">
  <h3 class='display-1'>New <%= @report.category_str %> Report</h3>
<div class="well">

  <%= render "form#{@report.category}" %>

</div>
</div>